name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release_job:
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v1
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: New release of clx-rm-groups ${{ github.ref_name }}
          draft: true
          prerelease: false
          body_path: CHANGELOG.md

  upload_release_assets_job:
    strategy:
      matrix:
        version: [ { os: ubuntu-20.04, suffix: x86_64, extension: '' }, { os: windows-latest, suffix: win64, extension: '.exe' }, { os: macos-latest, suffix: macos, extension: '' }]

    runs-on: ${{ matrix.version.os }}
    needs: create_release_job
    steps:
      - uses: actions/checkout@v1

      - name: Build release
        run: g++ -std=c++11 clx-rm-groups.cpp -o clx-rm-groups

      - name: Prepare assets
        run: |
          zip clx-rm-groups-${{ matrix.version.suffix }}.zip clx-rm-groups${{ matrix.version.extension }}

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release_job.outputs.upload_url }}
          asset_path: ./clx-rm-groups-${{ matrix.version.suffix }}.zip
          asset_name: clx-rm-groups-${{ matrix.version.suffix }}.zip
          asset_content_type: application/zip

